# Generated by Django 2.1.4 on 2019-01-05 18:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music_up_down_load', '0002_auto_20190104_0229'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User1',
        ),
    ]
