# Generated by Django 2.1.4 on 2019-01-05 18:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music_up_down_load', '0004_user1'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User1',
        ),
    ]
