# Generated by Django 2.1.4 on 2019-01-07 10:16

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('music_up_down_load', '0006_user1'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user1',
            managers=[
                ('users', django.db.models.manager.Manager()),
            ],
        ),
    ]
