# Generated by Django 2.1.4 on 2019-02-04 18:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music_up_down_load', '0007_auto_20190107_1216'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User1',
        ),
    ]
