# Generated by Django 2.1.4 on 2019-04-03 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_core', '0004_musiclist'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MusicList',
        ),
        migrations.AddField(
            model_name='profile',
            name='music_category',
            field=models.CharField(choices=[('Rock', 'Rock'), ('Punk', 'Punk'), ('Pop', 'Pop'), ('Hip-Hop', 'Hip-Hop')], default='Rock', max_length=100),
        ),
    ]
