# Generated by Django 2.1.4 on 2019-04-03 09:56

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('users_core', '0005_auto_20190403_1248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='music_category',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Rock', 'Rock'), ('Punk', 'Punk'), ('Pop', 'Pop'), ('Hip-Hop', 'Hip-Hop')], max_length=21),
        ),
    ]
