# Generated by Django 2.1.4 on 2019-04-04 14:28

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('users_core', '0006_auto_20190403_1256'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='music_nature',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Drummer', 'Drummer'), ('Τραγουδιστής', 'Τραγουδιστής'), ('Κιθαρίστας', 'Κιθαρίστας'), ('Μπασίστας', 'Μπασίστας'), ('Στιχουργός', 'Στιχουργός')], default='Χωρίς ιδιότητα', max_length=52),
        ),
    ]
