# Generated by Django 2.1.4 on 2019-04-05 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_core', '0008_auto_20190405_1747'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='music_upload',
        ),
        migrations.AddField(
            model_name='profile',
            name='uploaded_music',
            field=models.FileField(blank=True, upload_to='uploaded_music'),
        ),
    ]
