# Generated by Django 2.1.4 on 2019-04-06 17:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users_core', '0009_auto_20190405_1810'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='uploaded_music',
        ),
    ]
