# Generated by Django 2.1.4 on 2019-04-08 11:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users_core', '0011_songlist'),
    ]

    operations = [
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users_core.Profile')),
            ],
        ),
        migrations.RemoveField(
            model_name='songlist',
            name='profile',
        ),
        migrations.DeleteModel(
            name='SongList',
        ),
    ]
