# Generated by Django 2.1.4 on 2019-05-09 13:09

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('users_core', '0026_lyrics'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='birth_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='music_nature',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('Drummer', 'Drummer'), ('Songer', 'Songer'), ('Guitarist', 'Guitarist'), ('Bassist', 'Bassist'), ('Lyricist', 'Lyricist ')], max_length=41),
        ),
    ]
