# Generated by Django 2.1.4 on 2019-05-19 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_core', '0027_auto_20190509_1609'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='delete',
            field=models.BooleanField(default=False),
        ),
    ]
