# Generated by Django 2.1.4 on 2019-05-20 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users_core', '0028_song_delete'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='delete',
        ),
    ]
