# Generated by Django 2.1.4 on 2019-05-20 15:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_core', '0029_remove_song_delete'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lyrics',
            name='lyrics',
            field=models.FileField(blank=True, upload_to='uploaded_lyrics', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])]),
        ),
        migrations.AlterField(
            model_name='song',
            name='composition',
            field=models.FileField(blank=True, upload_to='uploaded_music', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp3', 'flac', 'wav'])]),
        ),
    ]
