# Generated by Django 2.1.4 on 2019-05-21 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_core', '0031_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rating',
            name='content_type',
        ),
        migrations.AddField(
            model_name='song',
            name='is_public',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='Rating',
        ),
    ]
