# Generated by Django 2.1.4 on 2019-05-25 20:15

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('users_core', '0032_auto_20190521_1731'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='music_category',
        ),
        migrations.AddField(
            model_name='profile',
            name='rock',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('Classic Rock', 'Classic Rock'), ('Progressive Rock', 'Progressive Rock'), ('Post Rock', 'Post Rock'), ('Rock&Roll', 'Rock&Roll'), ('Psychedelic Rock', 'Psychedelic Rock'), ('Hard Rock', 'Hard Rock'), ('Garage Rock', 'Garage Rock'), ('Surf Rock', 'Surf Rock'), ('Instrumental Rock', 'Instrumental Rock'), ('Math Rock', 'Math Rock'), ('Rockabilly', 'Rockabilly'), ('Punk', 'Punk'), ('Pop', 'Pop'), ('Hip-Hop', 'Hip-Hop')], max_length=154),
        ),
        migrations.AlterField(
            model_name='profile',
            name='music_nature',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('Drummer', 'Drummer'), ('Singer', 'Singer'), ('Guitarist', 'Guitarist'), ('Bassist', 'Bassist'), ('Lyricist', 'Lyricist ')], max_length=41),
        ),
    ]
