# Generated by Django 2.1.4 on 2019-05-28 18:55

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('users_core', '0035_auto_20190528_1801'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='blues',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('Blues Rock', 'Blues Rock'), ('Country Blues', 'Country Blues'), ('Rythm & Blues', 'Rythm & Blues'), ('Electric Blues', 'Electric Blues'), ('Boogie-Woogie', 'Boogie-Woogie'), ('Bluegrass', 'Bluegrass'), ('Delta Blues', 'Delta Blues')], max_length=89),
        ),
        migrations.AddField(
            model_name='profile',
            name='electronic',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('House', 'House'), ('Electronica', 'Electronica'), ('Downtempo', 'Downtempo'), ('Techno', 'Techno'), ('Electro', 'Electro'), ('Dubstep', 'Dubstep'), ('Drum % Bass', 'Drum % Bass'), ('Trance', 'Trance'), ('Dub', 'Dub'), ('Vaporwave', 'Vaporwave')], max_length=83),
        ),
        migrations.AddField(
            model_name='profile',
            name='funk',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('Funk', 'Funk'), ('Funk Jam', 'Funk Jam'), ('Deep Funk', 'Deep Funk'), ('Funk Rock', 'Funk Rock'), ('Jazz Funk', 'Jazz Funk'), ('g-Funk', 'g-Funk'), ('Electro Funk', 'Electro Funk'), ('Go-go', 'Go-go')], max_length=69),
        ),
        migrations.AddField(
            model_name='profile',
            name='greek',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('Έντεχνο', 'Έντεχνο'), ('Λαϊκό', 'Λαϊκό'), ('Ρεμπέτεκο', 'Ρεμπέτεκο')], max_length=23),
        ),
        migrations.AddField(
            model_name='profile',
            name='hiphop_rap',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('Rap', 'Rap'), ('Trap', 'Trap'), ('Instrumental Hip-Hop', 'Instrumental Hip-Hop'), ('Boom-Bap', 'Boom-Bap'), ('Beat-tape', 'Beat-tape')], max_length=48),
        ),
        migrations.AddField(
            model_name='profile',
            name='jazz',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('Jazz', 'Jazz'), ('Nu Jazz', 'Nu Jazz'), ('Modern Jazz', 'Modern Jazz'), ('Free Jazz', 'Free Jazz'), ('Soul Jazz', 'Soul Jazz'), ('Swing', 'Swing'), ('Latin Jazz', 'Latin Jazz'), ('Vocal Jazz', 'Vocal Jazz'), ('Spiritual Jazz', 'Spiritual Jazz')], max_length=87),
        ),
        migrations.AddField(
            model_name='profile',
            name='metal',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('Black Metal', 'Black Metal'), ('Death Metal', 'Death Metal'), ('Thrash Metal', 'Thrash Metal'), ('Doom Metal', 'Doom Metal'), ('Progressive Metal', 'Progressive Metal'), ('Sludge Metal', 'Sludge Metal'), ('Heavy Metal', 'Heavy Metal'), ('Metalcore', 'Metalcore'), ('Grindcore', 'Grindcore')], max_length=110),
        ),
        migrations.AddField(
            model_name='profile',
            name='other',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('Ska', 'Ska'), ('No Wave', 'No Wave'), ('Folk', 'Folk'), ('New wave', 'New wave'), ('Swing', 'Swing'), ('Gospel', 'Gospel')], max_length=38),
        ),
        migrations.AddField(
            model_name='profile',
            name='pop',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('Indie Pop', 'Indie Pop'), ('Synth Pop', 'Synth Pop'), ('Power Pop', 'Power Pop'), ('Dream Pop', 'Dream Pop'), ('Noise Pop', 'Noise Pop'), ('Experimental Pop', 'Experimental Pop'), ('Jangle Pop', 'Jangle Pop')], max_length=77),
        ),
        migrations.AddField(
            model_name='profile',
            name='punk',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('Punk Rock', 'Punk Rock'), ('Pop Punk', 'Pop Punk'), ('Garage Punk', 'Garage Punk'), ('Hardcore Punk', 'Hardcore Punk'), ('Thrash Punk', 'Thrash Punk'), ('Crust Punk', 'Crust Punk'), ('Folk Punk', 'Folk Punk'), ('Ska Punk', 'Ska Punk')], max_length=86),
        ),
        migrations.AddField(
            model_name='profile',
            name='soul',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('Soul', 'Soul'), ('Neo-Soul', 'Neo-Soul'), ('Gospel', 'Gospel')], max_length=20),
        ),
    ]
